- planning/poste/fonctions.php
- planning/poste/importer.php
- themes/default/default.css
MT 24616 : 
- Don't import agents if they are on leave and 'import absents' checkbox not checked
- Check 'import absents' by default
- Change CSS class cel-red to out-of-work-time
- Fix wrong marking of absences in plannings
> Don't import agents if they are on leave and 'import absents' checkbox not checked, check 'import absents' by default

- setup/maj.php
Fix errors in setup/maj.php
- correctly compares the current version with version 2.0
- doesn't create tables if they already exist (absences_recurrentes, responsables, volants)
> Fix errors in setup/maj.php

- composer.json
Add the name planningbiblio/planningbiblio to composer.json
in order to register the project on https://packagist.org
in order to use `composer create-project planningbiblio/planningbiblio`
> Add the name planningbiblio/planningbiblio to composer.json

- planning/poste/ajax.notes.php
- planning/poste/comment.php
- planning/poste/index.php
- setup/atomicupdate/20191021_add_config_planning_always_comment.php
- setup/db_data.php
Currently, the planning comments are only displayed if said planning is started
or validated.
A new configuration option has been introduced:
"Planning-CommentairesToujoursActifs" (disabled by default)
When enabled, planning comments are always displayed, regardless of said
planning status.
Test plan:
- Disable Planning-CommentairesToujoursActifs
- Check that the planning comments are not displayed when said planning
is not started or is not validated
- Enable Planning-CommentairesToujoursActifs
- Check that the planning comments are displayed even when said planning
is not started or is not validated
> MT 26914 [Planning]: Allow planning comments to be always displayed.

- absences/ajouter.php
- absences/infos.php
- agenda/index.php
- conges/modif.php
- js/script.js
- planning/poste/class.planning.php
Corrige quelques bugs constatés sur la version 19.10.xx
Ces bugs ne sont pas liés aux nouveautés de la 19.10 et existaient sur les versions précédentes
1./ Correction de l'agenda. Étaient marquées en rouge barré les plages de SP importées en dehors des heures de présences. Elles doivent être affichées normalement dans l'agenda (en noir), car ces plages sont bien occupées. Le marquage de couleur des plages importées en dehors des heures de présence ne concerne que le planning principal.
Bug depuis version 19.04
Correction : 0da86a0
2./ Les agents ayant le statut "administratif" (dans le champ "service public / administratif") pouvaient demander des congés mais ceux-ci ne pouvaient pas être validés car les agents admin étaient exclus de la liste. Lors de la validation, leur nom était …
> 19.10.bugfix2

- public/js/script.js
Fix the reset ICS URL function (20.10.xx only)
TEST PLAN
- Enable config ICS-EXPORT
- Go to My Account / ICS Calendar
- Click on the reset URL link
> Fix the reset ICS URL function (20.10.xx only)

- public/ics/ics-parser/class.iCalReader.php
- src/Cron/Legacy/cron.ics.php
MT32775 : ICS parser gets the right date when the TimeZone contains ":"
Also move cron.ics.php from public/ics to src/Cron/Legacy
> MT32775 : ICS parser gets the right date when the TimeZone contains ":"

- public/ics/ics-parser/class.iCalReader.php
- src/Cron/Legacy/cron.ics.php
MT32775 : ICS parser gets the right date when the TimeZone contains ":"
Also move cron.ics.php from public/ics to src/Cron/Legacy
> MT32775 : ICS parser gets the right date when the TimeZone contains ":" (20.10.xx)

- src/PlanningBiblio/MSGraphClient.php
Outlook <-> PlanningBiblio synchronization through MS Graph API: Use event id instead of iCalUId to check for empty events
> MT36024: Use event id instead of iCalUId to check for empty events

- src/Cron/PurgeLogTable.php
PurgeLogTable throws an error :
> In PurgeLogTable.php line 47:
>                                                                                              
>   Attempted to call an undefined method named "rowCount" of class "Doctrine\DBAL\Statement".
The script purges the logs from the database correctly but the error prevents it to log the execution.
Seems like rowCounts() must be called on the result of the query and not the Statement.
> Fix rowCounts error

- public/setup/atomicupdate/MT39656.php
- public/setup/db_data.php
- public/setup/maj.php
- This is necessary to prevent the script from being executed during the update
- Also add the script holiday_reset_comp_time to the cron tab in db_data.php
- Also rename holliday to holiday in comments
> MT39656: Holiday reset script: add the last value for holiday_reset_comp_time

- public/setup/atomicupdate/MT39656.php
- public/setup/db_data.php
- public/setup/maj.php
- This is necessary to prevent the script from being executed during the update
- Also add the script holiday_reset_comp_time to the cron tab in db_data.php
- Also rename holliday to holiday in comments
> MT39656: Holiday reset script: add the last value for holiday_reset_cmp_time

- src/Controller/OvertimeController.php
Test plan:
1) Set Recup-DelaiDefaut (Conges section) to blank or to a non-integer value.
2) Without the patch, check that a new overtime request triggers a JS error.
3) With the patch, check that there is no JS error.
(Recup-DelaiDefaut is set to 0)
> MT39696: Set Recup-DelaiDefaut to 0 if not correctly set.

- src/Controller/AgentController.php
Test plan:
1) without the patch, edit an agent and blank one value or more in the
holidays tab.
2) Check that saving fails.
3) With the patch, edit an agent and blank one value or more in the
holidays tab.
4) Check that saving works and that the values have been defaulted to 0.
> MT39491: Fix save agent save when holidays values are empty

- templates/absences/index.html.twig
TEST PLAN : 
Afficher la liste des absences
Sans cette PR : les dates de demande d'absence sont affichées sans les heures
Avec cette PR : les dates de demande d'absence sont affichées avec les heures et minutes (format d/m/Y H:i)
> MT39958: Display the time of absence registrations

- src/Controller/OvertimeController.php
In some cases (network hiccups for example), the POST request for editing an overtime can be sent twice.
This patch adds a minimum delay between two edits of a given overtime of 1 second by default.
This value can be overridden with the following setting in custom_options.php:
$config['post_requests_throttle'] = n;
Test plan:
1) Set post_requests_throttle to a large enough value in custom_options.php
(20 seconds should be enough)
2) Edit an overtime, check that the modification is made.
3) Within the 20 seconds, edit this overtime again, check that the modification
is denied, with a message telling you to wait a few seconds before trying
again.
4) After the 20 seconds are expired, edit this overtime again, and check that
the modification is made.
> MT39895: Add throttle to overtime edits

- src/Controller/HolidayController.php
In some cases (network hiccups for example), the POST request for editing an holiday can be sent twice, removing twice the number of holidays for the agent.
This patch adds a minimum delay between two edits of a given holiday of 1 second by default.
This value can be overridden with the following setting in custom_options.php:
$config['post_requests_throttle'] = n;
Test plan:
1) Set post_requests_throttle to a large enough value in custom_options.php
(20 seconds should be enough)
2) Edit an holiday, check that the modification is made.
3) Within the 20 seconds, edit this holiday again, check that the modification
is denied, with a message telling you to wait a few seconds before trying
again.
4) After the 20 seconds are expired, edit this holiday again, and check that
the modification is …
> MT39034: Add throttle to holiday edits

- public/absences/js/voir.js
test plan : 
Search absences with the default dates : 
- Without this PR : alert please select more than  year
- With this PR : OK
> MT40252: don't show the alert "please select more than 1 year" on leap years

- public/include/class.menu.php
- public/setup/atomicupdate/MT39693.php
- public/setup/db_data.php
- tests/Class/ClassMenuTest.php
Test plan:
- Run the SQL update (public/setup/updatedatabase.php)
- Check that "Jours de fermeture" (/closingday) is displayed in the
Administration menu only if Planook is disabled and Conges-Enable is enabled.
> MT39693: Show closingday in menu only if Conges-Enable is enabled

- src/Twig/AppExtension.php
See MT https://suivi.biblibre.com/view.php?id=39412#c227255
TEST PLAN : 
* create a planning for february, 1st
* display the week view
* - Without this PR, the date is displayed with html tags (sup)
* - With this PR, the date is well displayed (you may need to clear the server cache with `php bin/console cache:clear`)
With this PR, also check the folowings : 
* date displayed on planning day view for february, 1st
* date displayed on top of the dropdown menu "Choisissez un tableau" for february, 1st
* dates displayed in overtime form.
> MT39412: the datefull twig filter now interpret html tags

- src/Controller/StatisticController.php
Test plan:
1) Apply the patch
2) Go to time statistics (Statistiques -> Feuille de temps) 
3) Check that when a position is not part of a group, the hours are correctly displayed in the "Autres" category (both in the day column and on its own column)
> MT38947: Fix display of groups-free position in time statistics

- templates/planning/poste/index.html.twig
Test plan:
Without the patch:
- Enable Planning-CommentairesToujoursActifs
- Give only the "Modification des commentaires des plannings" to a user
- With this user, try to add a comment to an unvalidated planning
- Check that the "Ajouter un commentaire" button appears twice and has no effect.
With the patch:
- In the same conditions, check that you can add a comment.
> MT39966: Fix comments display under plannings

- public/absences/js/voir.js
This alert is still there when we chose the following dates : 2023-03-31 - 2024-03-31
> MT40252: don't show the alert "select more than 1 year", follow up

- public/absences/class.absences.php
- src/Controller/AbsenceController.php
- src/Model/Agent.php
- tests/Model/AgentTest.php
Test plan:
1) Without the patch, make sure that direct managers (Reponsables directs)
are checked in at least one of the absences notifications workflows
(Absences-notifications-* in the Absences tab of the configuration page)
2) For a user that has no direct managers, add an absence
3) Check that the message "`<li></li>`" is displayed before the message saying
that the absence has been added.
4) With the patch, check that the message "`<li></li>`" is gone.
This happens because there is an empty email in the list of recipients.
This patch fixes the problem in two ways:
- Make get_manager_emails return an empty array when there are no managers (and not an array with an empty value)
- Remove empty values in getRecipients* functions to make sure no empty emails are passed to the CJMail …
> MT39529: Fix erroneous message on absence add

- src/Controller/AgentController.php
- templates/agents/edit.html.twig
- MT39894: disable calendar synchronizations for new agents by default
- MT39894: harmonize the display of labels for calendar imports
> MT39894: disable calendar synchronizations for new agents by default

- public/conges/class.conges.php
- templates/conges/accounts.html.twig
Currently, /holiday/accounts (Congés -> Crédits) is always displayed in hours regardless of the Conges-Mode parameter.
Test plan:
1) Without the patch, values are always displayed in hours, even if
Conges-Mode is set to "jours"
2) With the patch, check that values are displayed accordingly to Conges-Mode
setting.
> MT41151: Allow /holiday/accounts to be displayed in days

- templates/statistics/absence.html.twig
Test plan:
- Disable PlanningHebdo
- Go to absence statistics (statistics/absence)
- Check that there a more columns than columns headers
- Apply the patch
- Check that the number of columns match the number of columns headers
> MT41068: Fix absence statistics display when PlanningHebdo is disabled

- public/ics/calendar.php
- public/ics/class.ics.php
- public/setup/atomicupdate/MT41030.php
- templates/help/index.html.twig
A new configuration is added: ICS-Interval, which is the number of days in the past to export ICS calendars from.
If ICS-Interval is not set, or set to a value that is not an integer, all events and/or absences in the past will be exported.
Regardless of ICS-Interval configuration, events in the future are still exported as before.
The configuration option ICS-Interval can be overridden by adding an interval parameter to the calendar URL:
Example: <URL>&interval=10
> MT41030: Allow to narrow ICS exports to a number of days in the past

- public/absences/js/modif.js
- templates/absences/add.html.twig
In order to prevent users from confusing an absence end date and its associated recurring absence end of series date, a warning is displayed when adding an absence with a recurring pattern if the absence end date is set and different from the absence start date.
> MT41028: Show an alert when a recurring absence is added and the enddate is set

- public/absences/js/modif.js
holidayAbsenceControl expects debut and fin parameters to be in the following format: hh:mm:ss
public/absences/js/modif.js passed them in a hh:mm format, causing wrong date comparison in SQL query.
> MT39946: Fix time format parameter for ajax call in absence add

- public/planning/poste/class.planning.php
Test plan:
- Without the patch, a right-click on a planning will not work if one of the agents in the right-click list has an utf8 first character (like an accent, "é" for example).
- With the patch, the right-click list will be shown, and the agent first name will be correctly shortened ("Émile" will become "É." for example).
> MT41411: Use utf8-aware function mb_substr (instead of substr) in plannings

- config/permissions.yaml
- public/absences/js/modif.js
- public/conges/class.conges.php
- public/conges/js/script.conges.js
- public/js/script.js
- public/setup/atomicupdate/MT41027.php
- public/setup/db_data.php
- public/setup/db_structure.php
- src/Controller/AbsenceBlockController.php
- src/Controller/AbsenceController.php
- src/Controller/AjaxController.php
- src/Model/AbsenceBlock.php
- src/PlanningBiblio/Helper/AbsenceBlockHelper.php
- templates/absenceBlock/edit.html.twig
- templates/absenceBlock/index.html.twig
- templates/conges/add.html.twig
A new configuration option "Absences-blocage" allows to define periods during which absences and holidays will be prevented from being added.
Administrators, however, will be warned with a message and will be able to override the blocking.
Test plan:
1) Enable "Absences-blocage" configuration option
2) Go to /absence/block (Absences -> Bloquer les absences)
3) Define one or more new periods
4) Check that you can edit and delete periods
5) Try to add or edit an absence or an holiday which overlaps in any way one
of the previoulsy defined periods
6) Check that, as a user, you cannot add or edit the absence or holiday
7) Check that, as an administrator, you have a warning message and are able to
override the blocking
> MT41027: Add absence block

- public/absences/js/modif.js
- templates/absences/add.html.twig
MT41028: Change the warning message for recurring absences with end date
La PR change le message pour 
"
Pour les absences récurrentes, la date de fin ne doit pas être saisie dans le formulaire d'absence mais dans la fenêtre de configuration de la récurrence.
Voulez-vous supprimer la date de fin choisie ?"
Et réduit la taille de la fenêtre.
> MT41028: Change the warning message for reccuring absences with end date

- src/Controller/StatisticController.php
- templates/statistics/agent.html.twig
- templates/statistics/service.html.twig
Test plan:
- Without the patch, the per-sites weekly averages in agent and service statistics are wrong (the weekly average for all sites is used)
- With the patch the per-sites weekly averages in agent and service statistics are correctly displayed
> MT41956: Fix weekly averages in agent and service statitics

- public/ics/class.ics.php
MT41894: Fix warning undefined array key VEVENT when importing ics calendars
> MT41894: Fix warning undefined array key VEVENT when importing ics calendars

- public/planning/poste/fonctions.php
> MT41650: Use utf8-aware function mb_substr (instead of substr) in plannings

- init/init_ajax.php
- public/absences/ajax.piecesJustif.php
- public/conges/ajax.enregistreRecup.php
- public/ics/ajax.resetURL.php
- public/include/ajax.menus.php
- public/include/db.php
- public/include/header.php
- public/include/sanitize.php
- public/ldap/ajax.ldaptest.php
- public/ldap/class.ldap.php
- public/personnel/ajax.delete.php
- public/personnel/ajax.sendICSURL.php
- public/personnel/ajax.update.php
- public/personnel/class.personnel.php
- public/planning/poste/ajax.appelDispoMail.php
- public/planning/poste/ajax.hiddenTables.php
- public/planning/poste/ajax.notes.php
- public/planning/poste/ajax.notifications.php
- public/planning/poste/ajax.updateCell.php
- public/planning/poste/ajax.validation.php
- public/setup/createconfig.php
- public/setup/createdb.php
- public/setup/fin.php
- public/statistiques/export.php
- src/Controller/FrameworkController.php
- src/Controller/IndexController.php
Remove some depreciations on PHP 8.1
test with PHP 8.1, APP_ENV=dev and APP_DEBUG=1.
Look for errors on var/log/dev.log : 
Focus on deprecated errors : `tail -n 30 -f var/log/dev.log | grep -i deprecated`
browse multiple pages
Compare this PR with master
> MT39367: Remove FILTER_SANITIZE_STRING depreciations

- public/absences/class.absences.php
- src/Controller/PlanningJobController.php
Test plan:
1) Have a teleworking reason with a character that must be escaped
Example: Garde d'enfants
2) Check that the context menu fails on planning cells using this reason
3) Apply the patch
4) Check that the context menu works
> MT42596: Escape teleworking reasons on planning context menu

- public/include/function.php
- tests/Include/IncludeFunctionTest.php
Test plan:
- Have a negative comp time credit of half an hour
- Without the patch, the display in 'My Account' shows -1h30
- With the patch, it correctly shows -0h30
Unit tests: tests/Include/IncludeFunctionTest.php
> MT40009: Fix comp time display in 'My Account' when negative

- public/setup/maj.php
- tools/fix_encoding_issues.php
- tools/remove_html_entities_from_absence_reasons.php
- setup/maj.php : Remove the column_exists function. Use IF NOT EXISTS instead.
- tools/remove_html_entities_from_absence_reasons.php : decode twice because we get doubly encoded strings.
The column_exists function was use before the queries was executed.
The results were not correct and its execution generated errors when the tables were not yet created.
Since release 23.10, db::select adds html entities.
We can then obtain doubly encoded strings in the remove_html_entities script.
Strings are now decode twice to get the expected result.
+ Add green [OK] and red [KO] to tool scripts
> MT42541: Fix migration scripts
