PlanningBiblio/PlanningBiblio

absences/ajax.control.php, absences/delete.php, absences/js/modif.js, include/maj.php, setup/db_data.php
Cette fonctionnalité fait suite à un besoin fonctionnel ressenti par l'équipe qui élabore le planning.
=> Ajout de l'option "Absences-planningVide"

postes/index.php
filtre sur les postes pour éviter de prendre en compte les lignes de séparation
=> filtre plus précis sur les postes pour permettre de supprimer ceux qui ont le même id que les lignes

index.php
=> MT 25112: Fix access rights when using multisites mode

init.php
=> MT 25112: Fix access rights when using multisites mode (2.8x branch)

ics/calendar.php, include/class.menu.php, init.php, planningHebdo/ajax.verifPlannings.php, planningHebdo/class.planningHebdo.php, planningHebdo/index.php, src/Model/Agent.php
This adds 3 patches form 2.8x branch:
=> 2.8 patches on master

templates/admin/config/category.html.twig
Update config template
Replace {{ v.commentaires }} with {{ v.commentaires | raw }}
to execute HTML code on comments
=> Update admin/config template

setup/atomicupdate/mt_25364.php, setup/maj.php, setup/updatedatabase.php
=> MT 25364: Fix a typo in PlanningHebdo-notifications-agent-par-agent's

ics/class.ics.php
Class ICS 
Initialization of id_origin
=> Initialization of id_origin

statistiques/agents.php, statistiques/postes.php, statistiques/postes_synthese.php, statistiques/samedis.php
=> Optimization of statistics

ics/class.ics.php
Improve ICS import
Make it compatible with Google invitations and the "Hamac" format
=> Ics update

planning/poste/importer.php
Bugfix : consider grey cells when importing schedule
=> Bugfix : consider grey cells when importing schedule

themes/default/default.css
Fix bug #91 : change css classes priority
=> Fix bug #91 : change css classes priority

src/Model/Agent.php
Fix misallocation of rights in multisites mode
=> Fix misallocation of rights in multisites mode

admin/config.php, setup/atomicupdate/20190713_update_config_cas_version.php, setup/db_data.php
=> Fix bug #86, CAS versions

authentification.php, include/function.php, personnel/password.php, personnel/valid.php, setup/atomicupdate/20190606_bcrypt_password.php, setup/db_structure.php, setup/fin.php
Hash passwords with password_hash() / bcrypt
Enhance security
=> Hash passwords with password_hash() / bcrypt

statistiques/service.php, statistiques/statut.php
Fix undefined indexes on statistiques/service.php & statut.php
=> Fix undefined indexes on statistiques/service.php & statut.php for 19.10.xx

src/Controller/AjaxController.php, src/Listener/ControllerAuthorizationListener.php, templates/agents/agent_table_edit.html.twig, templates/agents/edit.html.twig
- rename "change password" link in "send new password"
- add a link "change password"
test plan:
- go to agent/add/x,
- click on "change password" above link,
- type empty passwords
=> error,
- type different passwords
=> error,
- type valid passwords,
- save,
- try to login with the new password
=> Ability to change user password

ChangeLog.txt, config/packages/dev/web_profiler.yaml, install.sh, public/include/footer.php, public/include/header.php, public/setup/createconfig.php, public/setup/createdb.php, public/setup/fin.php, public/setup/index.php, templates/base.html.twig
Adaptation du Changelog : 
- mise en avant de la migration vers symfony
- suppression des fixes qui concernent la migration vers symfony car les bugs liés n'existaient pas sur les versions précédentes
Suppression du copyright dans le footer
Mis en conformité HTML 5 du DOCTYPE (il y avait des warnings dans les consoles de certains navigateurs)
=> Release 20.04

src/PlanningBiblio/MSGraphClient.php
- Fix getLocalEvents SQL query
- For some reason, calendarView returns events that have been deleted.
Each event is now checked (isEventEmpty function) before being added.
- For some reason, calendarView returns events that are outside of the
specified date range.
Each event is now checked for that matter before being added.
- Total amount of incoming and local events is now logged.
=> MT29665: Multiple fixes to MS Graph API import:

src/PlanningBiblio/MSGraphClient.php
This patch adds 4 retries when an error occurs during an Unirest request.
=> MT 30150: SSL errors can occur during MS Graph imports.

templates/agents/index.html.twig
Fix #432 , broken link to import agents from LDAP
=> Fix #432 , broken link to import agents from LDAP

src/Controller/ModelController.php
Test plan:
1) Without the patch, save a model
2) Save the model again, with the same name
3) In models administration, check that you have to delete it twice, which is
not normal
4) With the patch, save a model
5) Save the model again, with the same name
6) In models administration, check that you have to delete it only once
=> MT39548: Fix models deletion

templates/planning/poste/week.html.twig
=> MT39836: interpret html tags on comments in weekly view

init/init.php, public/init.php
MT40682: Correctly set displayed version
=> MT40682: Correctly set displayed version

public/absences/class.absences.php, src/Controller/StatisticController.php
MT40688: get better performance when displaying statistics on absences
=> MT40688: get better performance when displaying statistics on absences

src/Controller/StatisticController.php
MT40725/MT38947: Fix display of groups-free position in time statistics, Follow up
=> MT40725/MT38947: Fix display of groups-free position in time statistics, Follow up

src/Controller/StatisticController.php, templates/statistics/absence.html.twig
MT41168: Fix the site selection on statistics / absences
=> MT41168: Fix the site selection on statistics / absences

src/Controller/PlanningJobController.php
MT41094: Don't check journey time between areas when there is only one area
=> MT41094: Don't check journey time between areas when there is only one area

templates/menu.html.twig
=> MT40945: Fix the logo's link

public/js/CJScript.js, templates/statistics/time.html.twig
MT40851: Make Statistics/time table not responsive. Add the data-responsive property to CJDataTables
=> MT40851: Make Statistics/time table not responsive.

public/planning/poste/js/planning.js, src/Controller/IndexController.php
MT40199 : Remove the padlock when deleting plannings
=> MT40199 : Remove the padlock when deleting plannings

public/themes/default/default.css, templates/statistics/agent.html.twig, templates/statistics/position.html.twig, templates/statistics/service.html.twig, templates/statistics/status.html.twig, templates/statistics/supportposition.html.twig
MT41069: Show borders of all cells in statistics tables
=> MT41069: Show borders of all cells in statistics tables

public/absences/js/modif.js, public/conges/js/script.conges.js, public/js/script.js
MT41027: Add absence block, correctly define absence hours
=> MT41027: Add absence block, correctly define absence hours

src/Cron/ImportMSGraphCalendar.php
MT42098: importMSGraphCalendar return 0 on success
=> MT42098: importMSGraphCalendar return 0 on success

src/Controller/AuthorizationsController.php, src/EventListener/LoginListener.php
MT42339: Handle SSO tickets in the Login Listener
=> MT42339: Handle SSO tickets in the Login Listener

src/Controller/AgentController.php
- Fix call to Symfony\Component\EventDispatcher\EventDispatcher::dispatch
=> MT42179: Upgrade symfony from version 4.4 to 5.4

src/Controller/StatisticController.php, templates/statistics/service.html.twig, templates/statistics/status.html.twig
Test plan:
- Without the patch, empty columns are created for hours statistics
- With the pach, the columns are correctly populated
=> MT41957: Fix hours statistics by status

public/ics/class.ics.php
MT41845: Check invitation acceptance when importing ICS events
=> MT41845: Check invitation acceptance when importing ICS events

public/include/function.php, public/planningHebdo/class.planningHebdo.php, public/setup/atomicupdate/MT40171.php, public/setup/db_data.php, src/Controller/AgentController.php, src/Controller/AjaxController.php, src/PlanningBiblio/Notifier/Messages/create_account.php, templates/absences/edit.html.twig, templates/help/index.html.twig, tests/PlanningBiblio/NotifierTest.php
MT40171: Rename Planning Biblio to Planno
=> MT40171: Rename Planning Biblio to Planno

templates/admin/index.html.twig, tools/set_planook_config.sql, tools/unset_planook_config.sql
MT42693: Disable Absence Block on Planook config
=> MT42693: Disable Absence Block on Planook config

public/js/script.js, src/Controller/AbsenceInfoController.php, src/Controller/AdminInfoController.php, src/Controller/HolidayInfoController.php, src/Controller/ModelController.php, templates/admin/model/index.html.twig
MT41900: Replace HTTP method DEL with DELETE
=> MT41900: Replace HTTP method DEL with DELETE

composer.json, composer.lock, config/permissions.yaml, public/include/sanitize.php, public/planning/poste/ajax.notes.php, public/planning/poste/js/planning.js, src/Controller/AjaxController.php, tests/Include/IncludeSanitizeTest.php
Unit tests: tests/Include/IncludeSanitizeTest.php
=> MT42019: Use HTML Purifier to sanitize planning comments and model names

composer.json, composer.lock
MT42872: add symfony/mime to display attachments
=> MT42872: add symfony/mime to display attachments

public/statistiques/class.statistiques.php, public/statistiques/export.php, src/Controller/StatisticController.php
MT40023: Stats/Agent: Do not show agents never selected and not in selected sites
=> MT40023: Stats/Agent: Do not show agents never selected and not in selected sites

src/PlanningBiblio/Helper/HolidayHelper.php
MT40420: Fix the calculation of the free break
Test plan:
- For an agent that has working hours from 14:00 to 18:00 and one hour of
free break (which starts at 12 and ends at 14), add a full day holiday
- Without the patch, counted hours are 5 (incorrect)
- With the patch, counted hours are 3 (correct)
=> MT48517: Apply MT40420: Fix the calculation of the free break
